Template editor JSON exporting and importing
ansys/pydynamicreporting pull request #207
Opened 2024-12-17 18:19 UTC by zhang-yuanrui

This PR fulfill 2 parts of functionalities:
1. Exporting templates with hierarchy into a JSON file by the interface `get_templates_as_json`
2. Importing a JSON file and build the templates from the JSON by the interface `load_templates`

Things not done yet in this PR:
1. Checking comprehensive user errors when loading a JSON file. I did some basic JSON format error checking but not exhaustive.
2. Prompting users if they want to rename when loading a root template with the same name as the existing one.

Please note that: in this PR, `load_templates` is supposed to be working when given a correct JSON input, ideally, the original JSON file from `get_templates_as_json`

2024-12-17 21:51 UTC, margalva approved these changes

2024-12-17 22:30 UTC, viseshrp commented on src/ansys/dynamicreporting/core/utils/report_remote_server.py
> +    templates_data[curr_template_key] = {
I would suggest you get the attributes from the object's class instead

2024-12-17 22:35 UTC, viseshrp requested changes

2024-12-17 22:35 UTC, viseshrp commented on src/ansys/dynamicreporting/core/utils/report_remote_server.py
> +        "date": curr_template.date,
If you hardcode it this way, any new attribute will probably be missed out from this.

2024-12-17 22:35 UTC, viseshrp commented on src/ansys/dynamicreporting/core/utils/report_remote_server.py
> +        "date": curr_template.date,
Check the method from_db in `serverless/base.py` on how to get the fields.

2024-12-18 00:54 UTC, viseshrp commented on src/ansys/dynamicreporting/core/utils/report_remote_server.py
> +        "date": curr_template.date,
Here's another example https://github.com/ansys/pydynamicreporting/blob/82b592f1f49eea691c1b67cf3c1532ead1d67be0/src/ansys/dynamicreporting/core/serverless/base.py#L257

2024-12-18 04:51 UTC, viseshrp commented on tests/conftest.py
> +    use_local = pytestconfig.getoption("use_local_launcher")
I would avoid creating new fixtures just to add a few templates. If you are only testing new template examples, please add them to the existing database and use the existing fixtures instead.

2024-12-18 04:53 UTC, viseshrp requested changes

2024-12-18 04:53 UTC, viseshrp commented on tests/conftest.py
> +        cleanup_docker(request)
I merged an improvement to testing, so you may have to pull those and fix the merge conflicts. Also, fixtures are created slightly differently now. Check the new conftest.py.

2024-12-18 15:56 UTC, zhang-yuanrui commented on src/ansys/dynamicreporting/core/utils/report_remote_server.py
> +    fields = ["name", "report_type", "date", "tags", "item_filter"]
@viseshrp As I only need a subset of the attributes, I still hardcode over here but a bit better than previous way.

2024-12-18 16:02 UTC, zhang-yuanrui commented on tests/test_report_remote_server.py
> +def test_get_templates_as_json(adr_service_create) -> bool:
Use an existing fixture and populate templates manually.

2024-12-19 16:19 UTC, merged